### ISSUE TITLE
Tracking upstream MVP issues

### ISSUE THREAD

**Issue by iandunn** [WordPress/wporg-two-factor#1]
These are upstream issues that we want/need done during the MVP milestone.

### Harden

- [x] https://github.com/WordPress/two-factor/pull/473
- [x] https://github.com/WordPress/two-factor/pull/487
- [x] https://github.com/WordPress/two-factor/pull/495
- [x] https://github.com/WordPress/two-factor/pull/481
- [x] https://github.com/WordPress/two-factor/pull/502
- [x] https://github.com/WordPress/two-factor/pull/514
- [x] https://github.com/WordPress/two-factor/pull/482 and/or https://github.com/WordPress/two-factor/pull/510
- [x] https://github.com/WordPress/two-factor/pull/517

### Automated Testing

- [x] https://github.com/WordPress/two-factor/pull/469
- [x] https://github.com/WordPress/two-factor/pull/472
- [x] https://github.com/WordPress/two-factor/pull/474
- [x] https://github.com/WordPress/two-factor/pull/475

### Misc

- [x] https://github.com/WordPress/two-factor/pull/494
- [x] https://github.com/WordPress/two-factor/pull/504 - Blocker for our custom UI
- [x] Pin `two-factor` SVN external to a `trunk` revision after `504` merges, because it's currently pinned to Dion's branch
