### ISSUE TITLE
MVP launch tasks

### ISSUE THREAD

**Issue by iandunn** [WordPress/wporg-two-factor#16]
Here's a rough start, please add anything that's missing

- [x] Remove [the condition that prevents loading on production](https://github.com/WordPress/wporg-two-factor/blob/1b4f8ba66dc8ae9ec615bbdb8d6edcb7d35407c1/wporg-two-factor.php#L18-L21)
- [x] Finish parts of #26 that don't affect users who haven't opted in. It should only affect the beta users for now, and then it can be enabled for regular users in the next milestone.
- [x] [Enable for hardcoded list of beta users](https://github.com/WordPress/wporg-two-factor/blob/0e9017eef0a7c5d24156e11d7c1771fcdcf8849d/wporg-two-factor.php#L106-L108)
- [x] Add `wporg-two-factor` to wordcamp/buddypress SVN externals. Use URL of the `dotorg` SVN repo, not Github.
- [x] Remove [the manual inclusion of two-factor](https://github.com/WordPress/wporg-two-factor/blob/1b4f8ba66dc8ae9ec615bbdb8d6edcb7d35407c1/wporg-two-factor.php#L23-L24) (because the next step will activate it in a permanent way)
- [x] Network-activate both plugins on all networks in the w.org multi-network, wordcamp.org, buddypress.org, bbpress.org. Use an mu-plugin rather than relying on the DB options; see `mu-plugins/security.php` on w.org for example.
- [x] Run sync script
- [x] Deploy all on w.org
- [x] Deploy wordcamp
- [x] Finish #13 
- [x] [Review the milestone](https://github.com/WordPress/wporg-two-factor/milestone/1) for anything else that needs to happen
- [x] Do a few last minute manual end-to-end tests to make sure nothing broke recently
- [x] Security team review
- [x] Update the draft post to reflect #153
    - [x] Give instructions for setting up WebAuthn [if they already have wp-admin access](https://github.com/WordPress/wporg-two-factor/pull/153#issuecomment-1539273423)
    - [ ] Update draft to encourage [translating the WebAuthn plugin](https://translate.wordpress.org/projects/wp-plugins/two-factor-provider-webauthn/)?   
- [x] Publish launch post from #50

**Comment by StevenDufresne** [comment]
Posted: https://make.wordpress.org/meta/2023/05/31/two-factor-auth-available-to-test-on-wordpress-org/
