### ISSUE TITLE
Tracking upstream Iteration 1 issues

### ISSUE THREAD

**Issue by iandunn** [WordPress/wporg-two-factor#2]
These are upstream issues that we want/need done during the Iteration 1 milestone.

### Support hardware keys

#114 was a shortcut for the MVP, but long term we'll want to run 

- [x] #87 / #95 
- [x] Build rest of custom UI
- [ ] ~~https://github.com/WordPress/two-factor/pull/427 (or propose alternative)~~
- [ ] ~~https://github.com/WordPress/two-factor/pull/439 (optional, since it will be disabled by #14 anyway)~~
- [ ] ~~https://github.com/WordPress/two-factor/pull/491 (optional, it doesn't benefit us directly, but is somewhat necessary for the above ones)~~

### Security best practices

- [x] https://github.com/WordPress/two-factor/pull/510
- [x] https://github.com/WordPress/two-factor/pull/514
- [x] https://github.com/WordPress/two-factor/pull/517
- [x] https://github.com/WordPress/two-factor/issues/484
- [x] https://github.com/WordPress/two-factor/pull/482
- [x] https://github.com/WordPress/two-factor/pull/535
- [ ] ~~https://github.com/WordPress/two-factor/issues/455 / https://github.com/WordPress/two-factor/pull/389~~
- [ ] ~~https://github.com/WordPress/two-factor/issues/456 (optional since we can do it manually if needed)~~

### Misc

- [x] https://github.com/WordPress/two-factor/issues/516
- [x] https://github.com/WordPress/two-factor/pull/518
- [x] https://github.com/WordPress/two-factor/pull/519
- [x] https://github.com/WordPress/two-factor/pull/521
- [x] https://github.com/WordPress/two-factor/pull/522
- [x] https://github.com/WordPress/two-factor/pull/524
- [x] https://github.com/WordPress/two-factor/pull/525

**Comment by iandunn** [comment]
I moved some issues that don't seem like a high priority for this iteration to #240. Everything else has either been done, or doesn't need to be.
