### ISSUE TITLE
Tracking upstream Iteration 2 issues 

### ISSUE THREAD

**Issue by iandunn** [WordPress/wporg-two-factor#240]
These were migrated from #2 

### Security best practices

- [ ] https://github.com/WordPress/two-factor/pull/526
- [ ] https://github.com/WordPress/two-factor/issues/459
- [ ] https://github.com/WordPress/two-factor/issues/476
- [ ] https://github.com/WordPress/two-factor/pull/239 - contribute upstream work from #6, #17, etc
- [ ] https://core.trac.wordpress.org/ticket/43749 - This may help score weak passwords more strictly

### Misc

- [ ] https://github.com/WordPress/two-factor/issues/507
- [ ] https://github.com/WordPress/two-factor/issues/515
